<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- ALPHABETICAL --><!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),SC*,CM*,HN*,SN*,UF*,USE*,BT*,NT*,RT*,STA*,TYP*,INP*,APP*,UPD*,NVD*,TNR*,FLG*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT SC (#PCDATA)>
<!ELEMENT CM (#PCDATA)>
<!ELEMENT HN (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
<!ELEMENT STA (#PCDATA)>
<!ELEMENT TYP (#PCDATA)>
<!ELEMENT INP (#PCDATA)>
<!ELEMENT APP (#PCDATA)>
<!ELEMENT UPD (#PCDATA)>
<!ELEMENT NVD (#PCDATA)>
<!ELEMENT TNR (#PCDATA)>
<!ELEMENT FLG (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>[Distribution and sales methods]</DESCRIPTOR>
 <NT>Parts (Publishing)</NT>
 <STA>Approved</STA>
 <INP>2009-10-13</INP>
 <APP>2009-10-13</APP>
 <UPD>2009-10-13</UPD>
 <TNR>320</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>12mo format</NON-DESCRIPTOR>
 <USE>Duodecimo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>7</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>16mo format</NON-DESCRIPTOR>
 <USE>Sixteenmo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>9</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>18mo format</NON-DESCRIPTOR>
 <USE>Eighteenmo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>11</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>24mo format</NON-DESCRIPTOR>
 <USE>Twenty-fourmo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>13</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2o format</NON-DESCRIPTOR>
 <USE>Folio format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>1</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>32mo format</NON-DESCRIPTOR>
 <USE>Thirty-twomo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>15</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>4to format</NON-DESCRIPTOR>
 <USE>Quarto format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>3</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>64mo format</NON-DESCRIPTOR>
 <USE>Sixty-fourmo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>17</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>8vo format</NON-DESCRIPTOR>
 <USE>Octavo format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>5</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Accidental impressions</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for unintentional impressions made during the printing process.</SN>
 <BT>Pressman&apos;s work (Gathering term; do not assign)</BT>
 <NT>Bearer impressions</NT>
 <NT>Blind impressions</NT>
 <NT>Furniture impressions</NT>
 <NT>Offsets</NT>
 <NT>Slurs</NT>
 <NT>Space impressions</NT>
 <NT>Type-body impressions</NT>
 <STA>Approved</STA>
 <INP>2005-12-09</INP>
 <APP>2005-12-09</APP>
 <UPD>2014-05-16</UPD>
 <TNR>293</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Accidental type impressions</NON-DESCRIPTOR>
 <USE>Space impressions</USE>
 <USE>Type-body impressions</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>19</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Additions and corrections to text (Gathering term; do not assign)</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Cancellation</NT>
 <NT>Errata lists</NT>
 <NT>Insertions</NT>
 <NT>Press corrections</NT>
 <NT>Proofs</NT>
 <NT>States</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2007-08-03</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>277</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advance copies</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <BT>Special use copies (Gathering term; do not assign)</BT>
 <RT>Dummies</RT>
 <RT>Gratis copies</RT>
 <RT>Review copies</RT>
 <RT>Sample copies</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>22</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Auction prices</NON-DESCRIPTOR>
 <USE>Second-hand prices</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>27</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Authentication</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for the 18th century practice of having an author sign, stamp, or initial the title-page of a book as a protection against counterfeit editions</SN>
 <UF>Author statement in manuscript</UF>
 <BT>Fakery, falsification, imitation, and copying (Gathering term; do not assign)</BT>
 <RT>Copyright notices</RT>
 <RT>Forgeries</RT>
 <RT>Piracies</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>29</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Author statement in manuscript</NON-DESCRIPTOR>
 <USE>Authentication</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>30</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Backing-up</NON-DESCRIPTOR>
 <USE>Perfecting</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>34</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Bearer impressions</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for accidental impressions of roller or platen bearers</SN>
 <UF>Impressions, Bearer</UF>
 <BT>Accidental impressions</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-09</UPD>
 <TNR>36</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Bibles, thumb</NON-DESCRIPTOR>
 <USE>Thumb Bibles</USE>
 <STA>Approved</STA>
 <INP>2009-10-13</INP>
 <APP>2009-10-13</APP>
 <UPD>2009-10-13</UPD>
 <TNR>323</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Binding issues</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <BT>Issues</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>39</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Blad</NON-DESCRIPTOR>
 <USE>Sample copies</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>41</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Blind impressions</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC><!-- unknown line type [@@@] -->

 <SN>Use for accidental impressions of uninked bearer type on a blank page or part of a page.</SN>
 <UF>Impressions, blind</UF>
 <BT>Accidental impressions</BT>
 <STA>Approved</STA>
 <INP>2009-10-12</INP>
 <APP>2009-01-24</APP>
 <UPD>2009-10-16</UPD>
 <TNR>314</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Block books</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <UF>Xylographica</UF>
 <BT>Special shapes, sizes and kinds of books (Gathering term; do not assign)</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>42</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Blocks, inverted</NON-DESCRIPTOR>
 <USE>Inverted blocks</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-09</UPD>
 <TNR>44</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Blurs</NON-DESCRIPTOR>
 <USE>Slurs</USE>
 <STA>Approved</STA>
 <INP>2005-12-29</INP>
 <UPD>2005-12-29</UPD>
 <TNR>298</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book designers&apos; mock-ups</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <BT>Special use copies (Gathering term; do not assign)</BT>
 <RT>Dummies</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>46</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Book prices</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for original price only</SN>
 <UF>Prices of books</UF>
 <BT>Prices</BT>
 <RT>Second-hand prices</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-08</UPD>
 <TNR>47</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Books, Engraved</NON-DESCRIPTOR>
 <USE>Engraved books</USE>
 <STA>Approved</STA>
 <INP>2008-07-11</INP>
 <APP>2008-07-11</APP>
 <UPD>2008-07-11</UPD>
 <TNR>308</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Broadsheet format</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Broadside format</UF>
 <BT>Formats</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>51</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Broadside format</NON-DESCRIPTOR>
 <USE>Broadsheet format</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>52</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Calendar styles</NON-DESCRIPTOR>
 <USE>Imprint date styles</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>54</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancel gatherings</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for gatherings with altered text meant to replace text already printed, added to items after printing</SN>
 <UF>Cancellans gatherings</UF>
 <BT>Cancellation</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>56</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancel leaves</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for leaves with altered text meant to replace text already printed, added to items after printing</SN>
 <UF>Cancellans leaves</UF>
 <BT>Cancellation</BT>
 <RT>Inserted text leaves</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>59</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancel slips</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <UF>Label cancels</UF>
 <UF>Slip cancels</UF>
 <BT>Cancellation</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>62</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Cancellandum gatherings</NON-DESCRIPTOR>
 <USE>Cancelled gatherings</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>65</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Cancellandum leaves</NON-DESCRIPTOR>
 <USE>Cancelled leaves</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>67</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Cancellans gatherings</NON-DESCRIPTOR>
 <USE>Cancel gatherings</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>57</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Cancellans leaves</NON-DESCRIPTOR>
 <USE>Cancel leaves</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>60</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancellation</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <UF>Cancels</UF>
 <BT>Additions and corrections to text (Gathering term; do not assign)</BT>
 <BT>Editions, issues and states (Gathering term; do not assign)</BT>
 <NT>Cancel gatherings</NT>
 <NT>Cancel leaves</NT>
 <NT>Cancel slips</NT>
 <NT>Cancellation marks</NT>
 <NT>Cancelled gatherings</NT>
 <NT>Cancelled leaves</NT>
 <NT>Manuscript corrections</NT>
 <NT>Stamped corrections</NT>
 <RT>States</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-09</UPD>
 <TNR>58</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancellation marks</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Marks, Cancellation</UF>
 <BT>Cancellation</BT>
 <NT>Cancellation slits</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>70</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancellation slits</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Slits, Cancellation</UF>
 <BT>Cancellation marks</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>75</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancelled gatherings</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for gatherings meant to be removed but still present</SN>
 <UF>Cancellandum gatherings</UF>
 <BT>Cancellation</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>66</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cancelled leaves</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for leaves meant to be removed but still present</SN>
 <UF>Cancellandum leaves</UF>
 <BT>Cancellation</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>68</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Cancels</NON-DESCRIPTOR>
 <USE>Cancellation</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>69</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Casting off</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Composition</BT>
 <NT>Casting off errors</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>77</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Casting off errors</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Errors, Casting off</UF>
 <BT>Casting off</BT>
 <BT>Multiple printers</BT>
 <NT>Catchword irregularities</NT>
 <NT>Crowding</NT>
 <NT>Excess space</NT>
 <NT>Signing irregularities</NT>
 <NT>Type-size change</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-14</UPD>
 <TNR>79</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Catchword irregularities</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Irregular catchwords</UF>
 <BT>Casting off errors</BT>
 <BT>Catchwords</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>81</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Catchword patterns</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Catchwords</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>89</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Catchwords</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Direction lines</BT>
 <NT>Catchword irregularities</NT>
 <NT>Catchword patterns</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>88</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Chainlines, turned</NON-DESCRIPTOR>
 <USE>Turned chainlines</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-09</UPD>
 <TNR>91</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Chronograms</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Imprint date styles</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>93</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Cloth printings</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Special materials printings</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>94</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Colophons</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Printer identification (Gathering term; do not assign)</BT>
 <BT>Publisher identification (Gathering term; do not assign)</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>96</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Color printing</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Pressman&apos;s work (Gathering term; do not assign)</BT>
 <NT>Printing in a single color</NT>
 <NT>Printing in multiple colors</NT>
 <RT>Inking</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>97</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Colored paper printings</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Special materials printings</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>101</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Columniation</NON-DESCRIPTOR>
 <USE>Pagination</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>102</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Columniation errors</NON-DESCRIPTOR>
 <USE>Pagination errors</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>104</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Composition</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Setting type</UF>
 <UF>Typesetting</UF>
 <BT>Compositor&apos;s work (Gathering term; do not assign)</BT>
 <BT>Multiple printers</BT>
 <NT>Casting off</NT>
 <NT>Composition errors</NT>
 <NT>Compositor&apos;s copy</NT>
 <NT>Compositor&apos;s setting preferences</NT>
 <NT>Direction lines</NT>
 <NT>Headlines</NT>
 <NT>Justification</NT>
 <NT>Page-for-page reprints</NT>
 <NT>Page make-up</NT>
 <NT>Pagination</NT>
 <NT>Re-setting</NT>
 <NT>Setting order</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-14</UPD>
 <TNR>78</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Composition errors</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for dittography, omissions of text, misspelling, and any other compositorial errors.</SN>
 <UF>Errors, Composition</UF>
 <BT>Composition</BT>
 <NT>Dittography</NT>
 <NT>Text omissions</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-09</UPD>
 <TNR>111</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Compositor&apos;s copy</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for the manuscript or book from which the type was set</SN>
 <UF>Printer&apos;s setting copy</UF>
 <BT>Composition</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-08</UPD>
 <TNR>112</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Compositor&apos;s setting preferences</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for any evidence of compositorial preference in spelling, capitalization, punctuation, justification, etc.</SN>
 <UF>Compositor&apos;s style</UF>
 <BT>Composition</BT>
 <NT>Compositor&apos;s spelling preferences</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-08</UPD>
 <TNR>113</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Compositor&apos;s spelling preferences</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for any evidence of compositorial spelling preference</SN>
 <UF>Spelling preferences</UF>
 <BT>Compositor&apos;s setting preferences</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>119</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Compositor&apos;s style</NON-DESCRIPTOR>
 <USE>Compositor&apos;s setting preferences</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>118</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Compositor&apos;s work (Gathering term; do not assign)</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Composition</NT>
 <NT>Imposition</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2007-08-03</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>278</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Concealed editions</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <HN>Approved term 6/2007; UF &quot;hidden editions&quot; added 1/08</HN>
 <SN>Use for closely similar editions, printed from substantially different settings of type, not distinguished as such by the printer and/or publisher.</SN>
 <UF>Hidden editions</UF>
 <BT>Editions, issues and states (Gathering term; do not assign)</BT>
 <STA>Approved</STA>
 <INP>2007-06-28</INP>
 <APP>2007-06-28</APP>
 <UPD>2008-02-28</UPD>
 <TNR>299</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Control of printing (Gathering term; do not assign)</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Copyright and licensing</NT>
 <NT>Taxes and levies</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2007-08-03</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>279</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Control of publishing</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Copyright and licensing</NT>
 <NT>Taxes and levies</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2005-12-14</UPD>
 <TNR>287</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Copyright and licensing</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <BT>Control of printing (Gathering term; do not assign)</BT>
 <BT>Control of publishing</BT>
 <NT>Copyright notices</NT>
 <NT>Imprimaturs</NT>
 <NT>Printing privileges</NT>
 <NT>Statutory copies</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2005-12-14</UPD>
 <TNR>280</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Copyright notices</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Copyright and licensing</BT>
 <RT>Authentication</RT>
 <RT>Imprimaturs</RT>
 <RT>Printing privileges</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>31</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Corrected proofs</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Proofs</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>123</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Corrections in press</NON-DESCRIPTOR>
 <USE>Press corrections</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>125</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Corrections, Manuscript</NON-DESCRIPTOR>
 <USE>Manuscript corrections</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>127</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Corrections, Stamped</NON-DESCRIPTOR>
 <USE>Stamped corrections</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>128</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Counterfeits</NON-DESCRIPTOR>
 <USE>Forgeries</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>129</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Crowding</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Casting off errors</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>82</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Damaged printing plates</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for evidence of printing from plates that are worn or damaged.</SN>
 <UF>Plate damage</UF>
 <BT>Evidence</BT>
 <STA>Approved</STA>
 <INP>2015-04-21</INP>
 <APP>2015-04-21</APP>
 <UPD>2015-04-21</UPD>
 <TNR>330</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Damaged types</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <BT>Evidence</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-14</UPD>
 <TNR>130</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Dates of imprint</NON-DESCRIPTOR>
 <USE>Imprint date styles</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>132</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Dates of imprint, False</NON-DESCRIPTOR>
 <USE>False imprint dates</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>133</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Dating styles</NON-DESCRIPTOR>
 <USE>Imprint date styles</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>137</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Deposit copies</NON-DESCRIPTOR>
 <USE>Statutory copies</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>138</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Devices, Printers&apos;</NON-DESCRIPTOR>
 <USE>Printers&apos; devices</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>140</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Devices, Publishers&apos;</NON-DESCRIPTOR>
 <USE>Printers&apos; devices</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>142</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Direction lines</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for lines located directly below the text, mostly blank but containing catchwords, signatures, and/or press figures</SN>
 <BT>Composition</BT>
 <NT>Catchwords</NT>
 <NT>Press figures</NT>
 <NT>Signatures (Binder&apos;s notations)</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-12-08</UPD>
 <TNR>90</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Displaced types</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>Loose type</UF>
 <BT>Locking-up</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>145</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Distribution and sales methods (Gathering term; do not assign)</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Dummies</NT>
 <NT>Multiple publishers</NT>
 <NT>Part-issued books in volume form</NT>
 <NT>Prices</NT>
 <NT>Privately published books</NT>
 <NT>Series</NT>
 <NT>Subscribers&apos; addresses</NT>
 <NT>Subscription lists</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2009-10-13</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>288</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Dittography</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SN>Use for unintentional repetition of one or more letters, words, or lines in type-setting, as &quot;literatature&quot; for literature</SN>
 <BT>Composition errors</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>115</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Double printing</NON-DESCRIPTOR>
 <USE>Slurs</USE>
 <STA>Approved</STA>
 <INP>2005-12-29</INP>
 <UPD>2005-12-29</UPD>
 <TNR>297</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Drawback notices</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <BT>Taxes and levies</BT>
 <RT>Tax stamps</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>147</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Dummies</DESCRIPTOR>
 <SC>rbpub Publishing Terms</SC>
 <SN>Use for models of the type popular in the 19th century for the promotion and solicitation of sales for books, etc.</SN>
 <UF>Publishers&apos; dummies</UF>
 <UF>Salesmen&apos;s dummies</UF>
 <BT>Distribution and sales methods (Gathering term; do not assign)</BT>
 <BT>Special use copies (Gathering term; do not assign)</BT>
 <RT>Advance copies</RT>
 <RT>Book designers&apos; mock-ups</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-04-04</UPD>
 <TNR>23</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Duodecimo format</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>12mo format</UF>
 <UF>Twelvemo format</UF>
 <BT>Formats</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>8</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Editions, issues and states (Gathering term; do not assign)</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <SC>rbpub Publishing Terms</SC>
 <SN>Gathering term; do not use; index under a narrower term.</SN>
 <NT>Cancellation</NT>
 <NT>Concealed editions</NT>
 <NT>Errata lists</NT>
 <NT>Insertions</NT>
 <NT>Issues</NT>
 <NT>Limitation statements</NT>
 <NT>Multiple publishers</NT>
 <NT>Piracies</NT>
 <NT>Privately published books</NT>
 <NT>States</NT>
 <STA>Approved</STA>
 <INP>2005-04-04</INP>
 <APP>2005-04-04</APP>
 <UPD>2009-10-16</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>289</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Eighteenmo format</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <UF>18mo format</UF>
 <UF>Octodecimo format</UF>
 <BT>Formats</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2005-02-25</UPD>
 <TNR>12</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Engraved books</DESCRIPTOR>
 <SC>rbpri Printing Terms</SC>
 <HN>Approved 6/2008</HN>