<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- ALPHABETICAL --><!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),SC*,CM*,HN*,SN*,UF*,USE*,BT*,NT*,RT*,STA*,TYP*,INP*,APP*,UPD*,NVD*,TNR*,FLG*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT SC (#PCDATA)>
<!ELEMENT CM (#PCDATA)>
<!ELEMENT HN (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
<!ELEMENT STA (#PCDATA)>
<!ELEMENT TYP (#PCDATA)>
<!ELEMENT INP (#PCDATA)>
<!ELEMENT APP (#PCDATA)>
<!ELEMENT UPD (#PCDATA)>
<!ELEMENT NVD (#PCDATA)>
<!ELEMENT TNR (#PCDATA)>
<!ELEMENT FLG (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>annotator</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the writer of manuscript annotations on a printed item.</SN>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>1</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>artist</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for conceiving, and perhaps also implementing, an original graphic design or work of art. Prefer &quot;illustrator&quot; for book illustrators.</SN>
 <UF>graphic technician</UF>
 <NT>colorist</NT>
 <NT>engraver</NT>
 <NT>etcher</NT>
 <NT>fore-edge painter</NT>
 <NT>illustrator</NT>
 <NT>lithographer</NT>
 <RT>book designer</RT>
 <RT>calligrapher</RT>
 <RT>cover designer</RT>
 <RT>draftsman</RT>
 <RT>photographer</RT>
 <RT>printmaker</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>3</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>assignee</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity to whom a license for printing or publishing has been transferred.</SN>
 <RT>copyright holder</RT>
 <RT>licensee</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>10</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>associated name</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use with a name associated with or found in an item or collection, but which cannot be determined to be that of a “former owner” or other relator indicative of provenance.</SN>
 <NT>annotator</NT>
 <NT>depositor</NT>
 <NT>donor</NT>
 <NT>former owner</NT>
 <NT>honoree</NT>
 <NT>inscriber</NT>
 <NT>lender</NT>
 <NT>signer</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>2</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>attributed name</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use to relate an author, artist, etc. to a work for which there is or once was substantial authority for designating that person as author, creator, etc.</SN>
 <UF>supposed name</UF>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>20</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>bearer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for an entity who carries or delivers a communication, order, or other message.</SN>
 <STA>Approved</STA>
 <INP>2017-07-10</INP>
 <APP>2017-07-10</APP>
 <UPD>2017-10-11</UPD>
 <TNR>124</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>binder</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>binding designer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>22</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>binding designer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <UF>designer of binding</UF>
 <RT>binder</RT>
 <RT>book designer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>23</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>blurb-writer</NON-DESCRIPTOR>
 <USE>blurb writer</USE>
 <STA>Approved</STA>
 <INP>2005-02-28</INP>
 <APP>2005-02-28</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>98</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>blurb writer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>1/05 Add term</HN>
 <SN>Use for the entity responsible for writing a commendation or testimonial for a work, which appears on or within the publication itself.</SN>
 <UF>blurb-writer</UF>
 <UF>blurber</UF>
 <UF>blurbist</UF>
 <STA>Approved</STA>
 <INP>2005-02-28</INP>
 <APP>2005-02-28</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>95</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>blurber</NON-DESCRIPTOR>
 <USE>blurb writer</USE>
 <STA>Approved</STA>
 <INP>2005-02-28</INP>
 <APP>2005-02-28</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>97</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>blurbist</NON-DESCRIPTOR>
 <USE>blurb writer</USE>
 <STA>Approved</STA>
 <INP>2005-02-28</INP>
 <APP>2005-02-28</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>96</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>book artist</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Proposed by Nina Schneider, 5/2011</HN>
 <SN>Use for an entity who conceives and perhaps also executes an artist&apos;s book.</SN>
 <STA>Approved</STA>
 <INP>2012-06-27</INP>
 <APP>2012-06-27</APP>
 <UPD>2012-06-27</UPD>
 <TNR>113</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>book designer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for the entire graphic design of a book, including arrangement of type and illustration, choice of materials, and process used.</SN>
 <UF>designer of book</UF>
 <RT>artist</RT>
 <RT>binding designer</RT>
 <RT>bookjacket designer</RT>
 <RT>type designer</RT>
 <RT>typographer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-12-14</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>7</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>book jacket designer</NON-DESCRIPTOR>
 <USE>bookjacket designer</USE>
 <STA>Approved</STA>
 <INP>2010-01-26</INP>
 <APP>2010-01-26</APP>
 <UPD>2012-06-27</UPD>
 <TNR>108</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>bookjacket designer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>SN and UFs approved 20100116; change term request, 200907</HN>
 <SN>Use for the entity responsible for the design of a dust  jacket.</SN>
 <UF>book jacket designer</UF>
 <UF>designer of book jacket</UF>
 <UF>designer of bookjacket</UF>
 <UF>dust jacket designer</UF>
 <RT>book designer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>26</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>bookplate designer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <UF>designer of bookplate</UF>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>30</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>bookseller</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>distributor</RT>
 <RT>publisher</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>32</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>bowdlerizer</NON-DESCRIPTOR>
 <USE>censor</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>35</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>calligrapher</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>artist</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>8</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>cartographer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>37</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>censor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for a censor, bowdlerizer, expurgator, etc., official or private.</SN>
 <UF>bowdlerizer</UF>
 <UF>expurgator</UF>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>36</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>channel</NON-DESCRIPTOR>
 <USE>medium</USE>
 <STA>Approved</STA>
 <INP>2005-04-01</INP>
 <APP>2005-04-01</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>100</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>clairvoyant</NON-DESCRIPTOR>
 <USE>medium</USE>
 <STA>Approved</STA>
 <INP>2005-04-01</INP>
 <APP>2005-04-01</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>101</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>collector</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for bringing together material from various sources, which has been arranged, described, and cataloged as a collection. The collector is neither the creator of the material nor the entity to whom manuscripts in the collection may have been addressed.</SN>
 <BT>former owner</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>39</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>collotyper</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <BT>electrotyper</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>40</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>colorer</NON-DESCRIPTOR>
 <USE>colorist</USE>
 <STA>Approved</STA>
 <INP>2009-10-13</INP>
 <APP>2009-10-13</APP>
 <UPD>2012-06-27</UPD>
 <TNR>107</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>colorist</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for applying color to drawings, prints, photographs, maps, etc.</SN>
 <UF>colorer</UF>
 <BT>artist</BT>
 <RT>illustrator</RT>
 <STA>Approved</STA>
 <INP>2009-10-13</INP>
 <APP>2009-07-11</APP>
 <UPD>2012-06-27</UPD>
 <TNR>106</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>commissioning body</NON-DESCRIPTOR>
 <USE>patron</USE>
 <STA>Approved</STA>
 <INP>2015-04-21</INP>
 <APP>2015-04-21</APP>
 <UPD>2015-04-21</UPD>
 <TNR>121</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>comp.</NON-DESCRIPTOR>
 <USE>compiler</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>43</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>compiler</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Expanded from abbreviated form 6/2012.</HN>
 <SN>Use for the entity responsible for producing a work or publication by selecting and putting together material from the works of various persons or bodies.</SN>
 <UF>comp.</UF>
 <RT>editor</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>42</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>compositor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <UF>typesetter</UF>
 <RT>printer</RT>
 <RT>typographer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>44</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>conservator</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Proposed by Christopher Cook; approved 1/2006</HN>
 <SN>Use for the entity responsible for documenting, preserving, or treating printed or manuscript material, works of art, artifacts, or specimens.</SN>
 <UF>preservationist</UF>
 <STA>Approved</STA>
 <INP>2005-12-29</INP>
 <APP>2005-12-29</APP>
 <UPD>2012-06-27</UPD>
 <TNR>103</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>contributor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for an entity responsible for contributing to a larger work, such as a monographic anthology, serial publication, or other compilation of individual works. Do not use for an entity whose sole function in relation to a work is editor, author, compiler, or translator.</SN>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>47</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>copier</NON-DESCRIPTOR>
 <USE>facsimilist</USE>
 <USE>forger</USE>
 <USE>scribe</USE>
 <USE>transcriber</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>48</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>copyright holder</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>assignee</RT>
 <RT>licensee</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>11</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>corrector</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity that corrected a manuscript, such as the scriptorium official who corrected the work of a scribe. For printed matter, use proofreader.</SN>
 <RT>proofreader</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>53</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>correspondent</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the writer or recipient of a letter or other communication.</SN>
 <NT>recipient</NT>
 <NT>sender</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2017-10-11</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>55</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>counterfeiter</NON-DESCRIPTOR>
 <USE>forger</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>57</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>cover designer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for the graphic design of a book cover, album cover, slipcase, box, container, etc. For the entity responsible for the graphic design of an entire book, use book designer; for book jackets, use bookjacket designer.</SN>
 <UF>designer of cover</UF>
 <RT>artist</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>58</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>dedicatee</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity to whom a book, manuscript, etc., is dedicated (NOT the recipient of a gift).</SN>
 <RT>dedicator</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>60</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>dedicator</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the author of a dedication, which may be a formal statement or in epistolary or verse form.</SN>
 <RT>dedicatee</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>61</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>deponent</NON-DESCRIPTOR>
 <USE>witness</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>62</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>depositor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for placing material in the physical custody of a library or repository without transferring the legal title.</SN>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-12-14</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>13</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of binding</NON-DESCRIPTOR>
 <USE>binding designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>24</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of book</NON-DESCRIPTOR>
 <USE>book designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>25</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of book jacket</NON-DESCRIPTOR>
 <USE>bookjacket designer</USE>
 <STA>Approved</STA>
 <INP>2010-01-26</INP>
 <APP>2010-01-26</APP>
 <UPD>2012-06-27</UPD>
 <TNR>109</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of bookjacket</NON-DESCRIPTOR>
 <USE>bookjacket designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>29</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of bookplate</NON-DESCRIPTOR>
 <USE>bookplate designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>31</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of cover</NON-DESCRIPTOR>
 <USE>cover designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>59</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>designer of type</NON-DESCRIPTOR>
 <USE>type designer</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>64</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>distributor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>bookseller</RT>
 <RT>printer</RT>
 <RT>publisher</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2015-04-21</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>33</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>donor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity who donates a book, manuscript, etc., to the present owner; donors to previous owners are designated as former owner or inscriber.</SN>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>14</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>draftsman</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for executing artistic or technical drawings.</SN>
 <RT>artist</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>66</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>dust jacket designer</NON-DESCRIPTOR>
 <USE>bookjacket designer</USE>
 <STA>Approved</STA>
 <INP>2010-01-26</INP>
 <APP>2010-01-26</APP>
 <UPD>2012-06-27</UPD>
 <TNR>110</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ed.</NON-DESCRIPTOR>
 <USE>editor</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>68</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>editor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Expanded from abbreviated form 6/2012.</HN>
 <SN>Use for the entity responsible for preparing for publication a work not primarily his/her/its own, such as by elucidating text, adding introductory or other critical matter, or technically directing an editorial staff.</SN>
 <UF>ed.</UF>
 <RT>compiler</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>67</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>electrotyper</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <BT>platemaker</BT>
 <NT>collotyper</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>41</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>engineer, paper</NON-DESCRIPTOR>
 <USE>paper engineer</USE>
 <STA>Approved</STA>
 <INP>2010-01-26</INP>
 <APP>2010-01-26</APP>
 <UPD>2012-07-26</UPD>
 <TNR>112</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>engraver</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <BT>artist</BT>
 <BT>printmaker</BT>
 <NT>metal-engraver</NT>
 <NT>wood-engraver</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>5</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>etcher</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <BT>artist</BT>
 <BT>printmaker</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>72</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>expurgator</NON-DESCRIPTOR>
 <USE>censor</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>38</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>eyewitness</NON-DESCRIPTOR>
 <USE>witness</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>73</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>facsimilist</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for executing a facsimile.</SN>
 <UF>copier</UF>
 <RT>scribe</RT>
 <RT>transcriber</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>49</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>fore-edge artist</NON-DESCRIPTOR>
 <USE>fore-edge painter</USE>
 <STA>Approved</STA>
 <INP>2012-07-26</INP>
 <APP>2012-07-26</APP>
 <UPD>2012-07-26</UPD>
 <TNR>115</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>fore-edge painter</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Submitted by Robert Maxwell, 3/2012.</HN>
 <SN>Use for the painter of a fore-edge painting.</SN>
 <UF>fore-edge artist</UF>
 <BT>artist</BT>
 <STA>Approved</STA>
 <INP>2012-07-26</INP>
 <APP>2012-07-26</APP>
 <UPD>2012-07-26</UPD>
 <TNR>114</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>forger</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <UF>copier</UF>
 <UF>counterfeiter</UF>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>50</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>former owner</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for an entity that previously owned an item. For an entity giving the item to the present owner, use &quot;donor.&quot;</SN>
 <UF>inscribee</UF>
 <BT>associated name</BT>
 <NT>collector</NT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>15</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>graphic technician</NON-DESCRIPTOR>
 <HN>Relator term &quot;Graphic technician&quot; used before March 1988 only.</HN>
 <USE>artist</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>4</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>honoree</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity in whose memory or honor a book, manuscript, etc. is donated.</SN>
 <UF>memorial</UF>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>16</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ill.</NON-DESCRIPTOR>
 <USE>illustrator</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-06-27</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>76</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>illuminator</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>illustrator</RT>
 <RT>rubricator</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>77</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>illustrator</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Expanded from abbreviated form 6/2012.</HN>
 <SN>Use for the entity responsible for conceiving, and perhaps also implementing, a design or illustration, usually to accompany a written text.</SN>
 <UF>ill.</UF>
 <BT>artist</BT>
 <RT>colorist</RT>
 <RT>illuminator</RT>
 <RT>rubricator</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>75</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>imprimatur</NON-DESCRIPTOR>
 <USE>licensor</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>79</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>indexer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for compiling an index.</SN>
 <STA>Approved</STA>
 <INP>2014-05-16</INP>
 <APP>2014-05-16</APP>
 <UPD>2014-05-16</UPD>
 <TNR>118</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>inscribee</NON-DESCRIPTOR>
 <USE>former owner</USE>
 <STA>Approved</STA>
 <INP>2012-07-26</INP>
 <APP>2012-07-26</APP>
 <UPD>2012-07-26</UPD>
 <TNR>116</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>inscriber</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity that signs a presentation statement.</SN>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>17</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>interlocutor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for an entity that takes part in a dialogue, conversation, or discussion. Do not use for participants in interviews, debates, or disputations.</SN>
 <STA>Approved</STA>
 <INP>2015-07-27</INP>
 <APP>2015-07-27</APP>
 <UPD>2015-07-27</UPD>
 <TNR>122</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>interviewee</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>interviewer</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>81</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>interviewer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <RT>interviewee</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>82</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>lender</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for permitting the temporary use of an item.</SN>
 <BT>associated name</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>18</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>licensee</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the original recipient of the right to print or publish.</SN>
 <RT>assignee</RT>
 <RT>copyright holder</RT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>12</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>licensor</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the signer of a license, imprimatur, etc.</SN>
 <UF>imprimatur</UF>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>80</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>lithographer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for preparing the stone or plate for lithographic printing, including a graphic artist creating a design directly on the surface from which printing will be done.</SN>
 <BT>artist</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>6</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>marbler</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <SN>Use for the entity responsible for marbling paper, cloth, leather, etc.</SN>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>83</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>medium</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <CM>Proposed by Laura O&apos;Keefe, 8/03. Although modern specialist usage recognizes distinctions among the functions of &quot;medium,&quot; &quot;psychic,&quot; &quot;channel,&quot; and &quot;clairvoyant,&quot; these terms appear to be less distinct in earlier works. This accounts for the inclusion of UFs that are not strictly equivalent according to specialists in psychic phenomena.</CM>
 <HN>Candidate term 12/03.</HN>
 <SN>Use for an entity who purports to communicate with spirits.</SN>
 <UF>channel</UF>
 <UF>clairvoyant</UF>
 <UF>psychic</UF>
 <STA>Approved</STA>
 <INP>2005-04-01</INP>
 <APP>2005-04-01</APP>
 <UPD>2012-12-14</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>99</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>memorial</NON-DESCRIPTOR>
 <USE>honoree</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>74</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>metal-engraver</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <BT>engraver</BT>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>70</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>observer</NON-DESCRIPTOR>
 <USE>witness</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>84</TNR>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>onlooker</NON-DESCRIPTOR>
 <USE>witness</USE>
 <STA>Approved</STA>
 <INP>2005-02-25</INP>
 <APP>2005-02-25</APP>
 <UPD>2012-07-26</UPD>
 <NVD>2000-01-01</NVD>
 <TNR>85</TNR>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>paper engineer</DESCRIPTOR>
 <SC>rbrel Relator Term</SC>
 <HN>Term accepted, 20100116; Candidate term, 201001 and 200907.</HN>